name: CI for Lost\'n\'Found

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14'

    - name: Build project
      run: sudo ./gradlew build

    - name: Run unit tests
      run: sudo ./gradlew test

