# This is a basic workflow that is manually triggered

name: CI/CD for Lost n Found App

on: 
  push:
    branches:
      - dev
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14'
        
    - name: Build project
      run: ./gradlew build
      
    - name: Run unit tests
      run: ./gradlew test
